######################################################
################# Setup Ceph #########################
######################################################
---

# Quick hack to get ssh keys working with ceph
# - name: SSH Key
#   copy:
#     src: "/root/.ssh/{{ item }}"
#     dest: "/root/.ssh"
#     mode: 0400
#   with_items:
#     - "id_rsa"
#     - "id_rsa.pub"
#   when: inventory_hostname in groups['master-servers']

- import_tasks: preflight.yml

- name: Ceph Deploy Block
  block:
    - import_tasks: files.yml
    - import_tasks: install.yml
    - import_tasks: setup.yml
    - import_tasks: deploy.yml
  when: kube_check_result is defined and kube_check_result.stdout == ""
