---
- name: Check Provisioner
  include_role:
    name: kubernetes/common
    tasks_from: kube_check
  vars:
    type: "pods"
    namespace: "kube-system"
    resource_name: ""
    label: "app=rbd-provisioner"