#######################################################
#################### Disable IPv6 #####################
#######################################################
---

- name: Disable IPv6 in SSHD
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: AddressFamily
    line: AddressFamily inet
  notify:
  - sshd restart

- name: Remove localhost6 from hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: localhost6
    state: absent