#######################################################
###################  Kubernetes Setup Master ###############
#######################################################
---

- import_tasks: preflight.yml

- name: Master Node Block
  block:
    - import_tasks: files.yml
    - import_tasks: init_cluster.yml
    - import_tasks: setup_master_node.yml
  when: kube_check_result is defined and kube_check_result.stdout == ""

- import_tasks: metallb.yml
- import_tasks: kube_dashboard.yml

...
