#######################################################
###################  Kubernetes Reset ###############
#######################################################
---
- name: Reset Kubernetes Cluster
  command: kubeadm reset
  register: kube_reset_result

- name: Remove Kubernetes Packages to clear cache
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: Stop Services
  systemd:
    name: docker
    state: stopped

- name: Remove Artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/cni
    - /var/lib/kubelet
    - /etc/cni
    - /etc/kubernetes

- name: Remove Interfaces
  shell: |
    if [ $(ifconfig | grep {{ item }} | wc -l ) -gt 0 ]; then
      ip link delete {{ item }};
    fi
  with_items:
    - flannel.1
    - cni0