# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---
- hosts: all
  tasks:
  roles:
    - common
    - chrony

- name: Configure kube master
  hosts: master-servers
  roles:
    - kubernetes/common
    - kubernetes/master
  tags:
  - kube-master

- name: Configure kube nodes
  hosts: nodes
  roles:
    - kubernetes/common
    - kubernetes/node
  tags:
  - add-node
  - kube-node

- name: Setup Ceph
  hosts: master-servers
  roles:
    - ceph
  tags:
  - ceph

- name: Deploy Elasticsearch
  hosts: master-servers
  roles:
    - elasticsearch
  tags:
  - elasticsearch

- name: Deploy Logstash
  hosts: master-servers
  roles:
    - logstash
  tags:
  - logstash

- name: Deploy Kibana
  hosts: master-servers
  roles:
    - kibana
  tags:
  - kibana

- name: Deploy Kafka
  hosts: master-servers
  roles:
    - kafka
  tags:
  - kafka

- name: Deploy Bro
  hosts: master-servers
  roles:
    - bro
  tags:
  - bro

- name: Deploy Moloch
  hosts: master-servers
  roles:
    - moloch
  tags:
  - moloch

- name: Deploy Suricata
  hosts: master-servers
  roles:
    - suricata
  tags:
  - suricata

...
